### ISSUE TITLE
Edit My Profile Link

### ISSUE THREAD

**Issue by AnneStefanyk** [badcamp/badcamp-2017-Sprint-Planning#175]
Need to place link to view/edit my profile

Not 100% sure where, but wanted to create an issue

**Comment by carsonblack** [comment]
Can't currently easily get tokens into menu paths in D8 because menu_token module is not there yet. Workaround just to get this out of the way is to provide a menu item fir users with sub items for login and logout. By clicking on user you will see the edit tab and be able to edit your profile from there.
