### ISSUE TITLE
Anonymous Users should be able to see Donate Page

### ISSUE THREAD

**Issue by AnneStefanyk** [badcamp/badcamp-2017-Sprint-Planning#182]
This is important we fix just after go live

https://test-badcamp-2017.pantheonsite.io/donate

This page should be viewable to Anon and when they click to donate it prompts to create an account

@carsonblack @sean-e-dietrich

**Comment by AnneStefanyk** [comment]
Note: Add link on this page /sponsorship and in menu item

**Comment by carsonblack** [comment]
The click to donate causing them to login isn't going to happen, because those buttons are not ours.

**Comment by carsonblack** [comment]
But I can make it so when they go to that page they are redirected to login.

**Comment by carsonblack** [comment]
Uh yeah. if anon goes to /donate they are prompted to login / create account. Destination to /donate is also appended to the path. But because they are not allowed to access the donate page a link in the menu to that path would not show for them. A hand made link somewhere else would though. I just don't want to cause a problem where someone without an account can create a payment. It could cause some problems with what we have at this point.
