### ISSUE TITLE
menu overlap at smaller desktop views

### ISSUE THREAD

**Issue by AnneStefanyk** [badcamp/badcamp-2017-Sprint-Planning#185]
<img width="1071" alt="nav1" src="https://user-images.githubusercontent.com/3211202/29379607-e0c40306-8277-11e7-8308-4117a3dcd114.png">

**Comment by jaymejohnson** [comment]
```@media print, screen and (min-width: 40em)
.menu.medium-horizontal {
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
   }
```

The culprit was this flex-wrap rule on the menu `<ul>`. It looks like it's been fixed, however, and that this rule is just lingering around in this temp file: https://2017.badcamp.net/sites/default/files/css/css_HaGnxCLG-Dfw5OVhMohcbPFoPeg9IOZWPwi4pkOP9Vg.css?ovq3z6

Once this temp file is flushed out, the issue should resolve itself. For a reference, see the dev site. I added enough links to the main menu to see how it behaves when it's the same size as the production site. https://dev-badcamp-2017.pantheonsite.io/

**Comment by AnneStefanyk** [comment]
@carsonblack this is approved to push
