### ISSUE TITLE
As a/an authenticated user, I want to update my user profile so that I can connect with other Drupalists at BADCamp.

### ISSUE THREAD

**Issue by kwhite** [badcamp/badcamp-2017-Sprint-Planning#41]
**Story ID:** 42

# Notes

# Acceptance Criteria
Fields include:
- Photo (default avatar if missing)
- Title
- Company
- Drupal.org username
- Twitter
- Facebook
- Bio

**Comment by shirazd** [comment]
This is the 3rd ticket I've had spec'ing fields for the user profile (basically they were dups of each other, but this is the one with the most fields).

- Title -- added
- Company -- we already had Organization, and I'm leaving it at that (more open)
- Drupal.org username - was already there
- Twitter and Facebook -- I've added this via a single multival field from the social_profile_field module, wherein user pastes their link and the module will determine which social network it is and render the appropriate icon on the view. That said, in my tests of Facebook, Twitter and Linked in, it only worked on FB, rendering a generic icon for the latter two. It's a newish module for D8 (more mature in D7) and seems to be the best one available so I thought to stick with it and we can ticket separately if we want to build out Twitter, LinkedIn, or whatever else detection. Otherwise it just generates a generic icon, as noted.
- Bio -- added (long plain text)
- photo -- interestingly, I had trouble with this, which I'm owing to my inexperience with D8. From what I gather, starting in D8 this is now a regular image field as opposed to core-provisioned specialized functionality. Which is great, except that the field is only added by the standard install profile, not the minimal install profile, which I believe is how this build was started. So to add it I used the avatars module, which seemed like my only option in D8, as when I tried to add the field natively in the fields UI on the user, it wants to preface the field name with "field_" whereas it seems that the Drupal code generally wants this field to be named "user_picture". In fact avatars module did provide the properly named field but then when I went to add images to profiles, the image would get dropped from the user on user view. I saw some people very similar-sounding issues, though not specific to avatar module. In the end I was taking a lot of time for this issue which should be simple and something I'm sure others are already aware of the correct method for, so I've left it out for now, and have ticketed separately: https://github.com/badcamp/badcamp-2017-Sprint-Planning/issues/97
